# This file contains the settings for the Command Reporter Plugin. For setting suspicious commands, head over to the "suspicious commands.yml" file.

discord:
  webhook-url: ""
  webhook-username: "Command Reporter"
  webhook-avatar-url: ""
  embed-color: "65280"
  embed-icon-url: "https://i.imgur.com/ZTuP6fGb.jpg"

  # Leave both of these empty if you don't want a footer.
  embed-footer-text: "Command Reporter Plugin"
  embed-footer-icon-url: ""

  # Specify the discord role that will be mentioned if a suspicious command is executed.
  # DO NOT INCLUDE THE @ SYMBOL
  admin-role: "everyone"